export const categories = [
  { id: "fiction", name: "Fiction", icon: "📖", description: "Explore imaginative stories and novels" },
  { id: "non-fiction", name: "Non-Fiction", icon: "📚", description: "Discover real-world knowledge and insights" },
  { id: "science", name: "Science", icon: "🔬", description: "Dive into scientific discoveries and theories" },
  { id: "romance", name: "Romance", icon: "💕", description: "Fall in love with heartwarming tales" },
  { id: "children", name: "Children's", icon: "🧒", description: "Magical stories for young readers" },
  { id: "mystery", name: "Mystery", icon: "🔍", description: "Unravel thrilling puzzles and secrets" },
  { id: "biography", name: "Biography", icon: "👤", description: "Inspiring life stories of notable people" },
  { id: "history", name: "History", icon: "🏛️", description: "Journey through the ages" },
]

export const books = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 14.99,
    originalPrice: 19.99,
    category: "fiction",
    rating: 4.5,
    reviews: 2847,
    description: "A story of the mysteriously wealthy Jay Gatsby and his love for Daisy Buchanan, set in the Jazz Age.",
    image: "/the-great-gatsby-classic-book-cover-elegant.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "2",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    price: 18.99,
    originalPrice: 24.99,
    category: "non-fiction",
    rating: 4.7,
    reviews: 5621,
    description: "A groundbreaking narrative of humanity's creation and evolution.",
    image: "/sapiens-book-cover-human-evolution.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "3",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    price: 16.99,
    originalPrice: 22.99,
    category: "science",
    rating: 4.6,
    reviews: 3892,
    description: "A landmark volume in science writing exploring the mysteries of the universe.",
    image: "/a-brief-history-of-time-space-cosmos-book.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "4",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 12.99,
    originalPrice: 16.99,
    category: "romance",
    rating: 4.8,
    reviews: 7234,
    description: "The beloved story of Elizabeth Bennet and Mr. Darcy.",
    image: "/pride-and-prejudice-classic-romance-book-cover.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "5",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    price: 15.99,
    originalPrice: 19.99,
    category: "children",
    rating: 4.9,
    reviews: 12456,
    description: "The magical adventure that started it all.",
    image: "/harry-potter-magical-wizard-book-cover.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "6",
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    price: 14.99,
    originalPrice: 18.99,
    category: "mystery",
    rating: 4.4,
    reviews: 4521,
    description: "A gripping mystery thriller that will keep you on the edge.",
    image: "/girl-with-dragon-tattoo-mystery-thriller-book.jpg",
    inStock: true,
    featured: false,
  },
  {
    id: "7",
    title: "Steve Jobs",
    author: "Walter Isaacson",
    price: 19.99,
    originalPrice: 25.99,
    category: "biography",
    rating: 4.5,
    reviews: 3245,
    description: "The exclusive biography of Apple's legendary founder.",
    image: "/steve-jobs-biography-book-cover-apple.jpg",
    inStock: true,
    featured: false,
  },
  {
    id: "8",
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    price: 17.99,
    originalPrice: 22.99,
    category: "history",
    rating: 4.3,
    reviews: 2876,
    description: "A short history of everybody for the last 13,000 years.",
    image: "/guns-germs-steel-history-civilization-book.jpg",
    inStock: true,
    featured: false,
  },
  {
    id: "9",
    title: "1984",
    author: "George Orwell",
    price: 13.99,
    originalPrice: 17.99,
    category: "fiction",
    rating: 4.7,
    reviews: 8934,
    description: "A dystopian masterpiece about surveillance and control.",
    image: "/1984-george-orwell-dystopian-book-cover.jpg",
    inStock: true,
    featured: false,
  },
  {
    id: "10",
    title: "The Cosmos",
    author: "Carl Sagan",
    price: 21.99,
    originalPrice: 27.99,
    category: "science",
    rating: 4.8,
    reviews: 4123,
    description: "A personal voyage through the universe.",
    image: "/cosmos-carl-sagan-space-universe-book.jpg",
    inStock: true,
    featured: false,
  },
  {
    id: "11",
    title: "The Notebook",
    author: "Nicholas Sparks",
    price: 11.99,
    originalPrice: 14.99,
    category: "romance",
    rating: 4.4,
    reviews: 5678,
    description: "An unforgettable love story that will touch your heart.",
    image: "/the-notebook-romance-love-story-book-cover.jpg",
    inStock: true,
    featured: false,
  },
  {
    id: "12",
    title: "Charlotte's Web",
    author: "E.B. White",
    price: 9.99,
    originalPrice: 12.99,
    category: "children",
    rating: 4.8,
    reviews: 6789,
    description: "The beloved story of friendship between a pig and a spider.",
    image: "/charlottes-web-children-book-farm-animals.jpg",
    inStock: true,
    featured: false,
  },
]

export function getBooksByCategory(categoryId) {
  return books.filter((book) => book.category === categoryId)
}

export function getFeaturedBooks() {
  return books.filter((book) => book.featured)
}

export function getBookById(id) {
  return books.find((book) => book.id === id)
}

export function searchBooks(query) {
  const lowerQuery = query.toLowerCase()
  return books.filter(
    (book) => book.title.toLowerCase().includes(lowerQuery) || book.author.toLowerCase().includes(lowerQuery),
  )
}
