// ==================================================
// BOOK MODEL - Data schema and operations for books
// ==================================================

let books = [
  {
    id: "1",
    title: "The Great Gatsby",
    authorId: "1",
    author: "F. Scott Fitzgerald",
    sellerId: "2",
    price: 14.99,
    originalPrice: 19.99,
    category: "fiction",
    genres: ["fiction"],
    rating: 4.5,
    reviewCount: 2847,
    description:
      "A story of the mysteriously wealthy Jay Gatsby and his love for Daisy Buchanan, set against the backdrop of the Jazz Age.",
    image: "/the-great-gatsby-classic-book-cover-elegant.jpg",
    inStock: true,
    quantity: 50,
    featured: true,
    isbn: "978-0-7432-7356-5",
    pages: 180,
    language: "English",
    publisher: "Scribner",
    publishedDate: "1925-04-10",
    status: "active",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "Sapiens: A Brief History of Humankind",
    authorId: "2",
    author: "Yuval Noah Harari",
    sellerId: "2",
    price: 18.99,
    originalPrice: 24.99,
    category: "non-fiction",
    genres: ["non-fiction", "history"],
    rating: 4.7,
    reviewCount: 5621,
    description: "A groundbreaking narrative of humanity's creation and evolution.",
    image: "/sapiens-book-cover-human-evolution.jpg",
    inStock: true,
    quantity: 35,
    featured: true,
    isbn: "978-0-06-231609-7",
    pages: 443,
    language: "English",
    publisher: "Harper",
    publishedDate: "2014-02-10",
    status: "active",
    createdAt: "2024-01-02T00:00:00Z",
  },
  {
    id: "3",
    title: "A Brief History of Time",
    authorId: "3",
    author: "Stephen Hawking",
    sellerId: "2",
    price: 16.99,
    originalPrice: 22.99,
    category: "science",
    genres: ["science", "non-fiction"],
    rating: 4.6,
    reviewCount: 3892,
    description: "A landmark volume in science writing exploring the mysteries of the universe.",
    image: "/a-brief-history-of-time-space-cosmos-book.jpg",
    inStock: true,
    quantity: 25,
    featured: true,
    isbn: "978-0-553-38016-3",
    pages: 212,
    language: "English",
    publisher: "Bantam",
    publishedDate: "1988-04-01",
    status: "active",
    createdAt: "2024-01-03T00:00:00Z",
  },
  {
    id: "4",
    title: "Pride and Prejudice",
    authorId: "4",
    author: "Jane Austen",
    sellerId: "2",
    price: 12.99,
    originalPrice: 16.99,
    category: "romance",
    genres: ["romance", "fiction"],
    rating: 4.8,
    reviewCount: 7234,
    description: "The beloved story of Elizabeth Bennet and Mr. Darcy.",
    image: "/pride-and-prejudice-classic-romance-book-cover.jpg",
    inStock: true,
    quantity: 40,
    featured: true,
    isbn: "978-0-14-143951-8",
    pages: 432,
    language: "English",
    publisher: "Penguin Classics",
    publishedDate: "1813-01-28",
    status: "active",
    createdAt: "2024-01-04T00:00:00Z",
  },
  {
    id: "5",
    title: "Harry Potter and the Sorcerer's Stone",
    authorId: "5",
    author: "J.K. Rowling",
    sellerId: "2",
    price: 15.99,
    originalPrice: 19.99,
    category: "children",
    genres: ["children", "fiction"],
    rating: 4.9,
    reviewCount: 12456,
    description: "The magical adventure that started it all.",
    image: "/harry-potter-magical-wizard-book-cover.jpg",
    inStock: true,
    quantity: 100,
    featured: true,
    isbn: "978-0-590-35340-3",
    pages: 309,
    language: "English",
    publisher: "Scholastic",
    publishedDate: "1997-06-26",
    status: "active",
    createdAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "6",
    title: "The Girl with the Dragon Tattoo",
    authorId: "6",
    author: "Stieg Larsson",
    sellerId: "2",
    price: 14.99,
    originalPrice: 18.99,
    category: "mystery",
    genres: ["mystery", "fiction"],
    rating: 4.4,
    reviewCount: 4521,
    description: "A gripping mystery thriller featuring the enigmatic Lisbeth Salander.",
    image: "/girl-with-dragon-tattoo-mystery-thriller-book.jpg",
    inStock: true,
    quantity: 30,
    featured: false,
    isbn: "978-0-307-47347-9",
    pages: 465,
    language: "English",
    publisher: "Vintage Crime",
    publishedDate: "2005-08-01",
    status: "active",
    createdAt: "2024-01-06T00:00:00Z",
  },
  {
    id: "7",
    title: "Steve Jobs",
    authorId: "7",
    author: "Walter Isaacson",
    sellerId: "2",
    price: 19.99,
    originalPrice: 25.99,
    category: "biography",
    genres: ["biography", "non-fiction"],
    rating: 4.5,
    reviewCount: 3245,
    description: "The exclusive biography of Apple's legendary co-founder.",
    image: "/steve-jobs-biography-book-cover-apple.jpg",
    inStock: true,
    quantity: 28,
    featured: false,
    isbn: "978-1-4516-4853-9",
    pages: 656,
    language: "English",
    publisher: "Simon & Schuster",
    publishedDate: "2011-10-24",
    status: "active",
    createdAt: "2024-01-07T00:00:00Z",
  },
  {
    id: "8",
    title: "Guns, Germs, and Steel",
    authorId: "8",
    author: "Jared Diamond",
    sellerId: "2",
    price: 17.99,
    originalPrice: 22.99,
    category: "history",
    genres: ["history", "non-fiction"],
    rating: 4.3,
    reviewCount: 2876,
    description: "A short history of everybody for the last 13,000 years.",
    image: "/guns-germs-steel-history-civilization-book.jpg",
    inStock: true,
    quantity: 22,
    featured: false,
    isbn: "978-0-393-31755-8",
    pages: 528,
    language: "English",
    publisher: "W. W. Norton",
    publishedDate: "1997-03-01",
    status: "active",
    createdAt: "2024-01-08T00:00:00Z",
  },
  {
    id: "9",
    title: "1984",
    authorId: "9",
    author: "George Orwell",
    sellerId: "2",
    price: 13.99,
    originalPrice: 17.99,
    category: "fiction",
    genres: ["fiction"],
    rating: 4.7,
    reviewCount: 8934,
    description: "A dystopian masterpiece about surveillance and control.",
    image: "/1984-george-orwell-dystopian-book-cover.jpg",
    inStock: true,
    quantity: 45,
    featured: false,
    isbn: "978-0-452-28423-4",
    pages: 328,
    language: "English",
    publisher: "Signet Classics",
    publishedDate: "1949-06-08",
    status: "active",
    createdAt: "2024-01-09T00:00:00Z",
  },
  {
    id: "10",
    title: "Cosmos",
    authorId: "10",
    author: "Carl Sagan",
    sellerId: "2",
    price: 21.99,
    originalPrice: 27.99,
    category: "science",
    genres: ["science", "non-fiction"],
    rating: 4.8,
    reviewCount: 4123,
    description: "A personal voyage through the universe.",
    image: "/cosmos-carl-sagan-space-universe-book.jpg",
    inStock: true,
    quantity: 18,
    featured: false,
    isbn: "978-0-345-53943-4",
    pages: 432,
    language: "English",
    publisher: "Ballantine Books",
    publishedDate: "1980-09-28",
    status: "active",
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "11",
    title: "The Notebook",
    authorId: "11",
    author: "Nicholas Sparks",
    sellerId: "2",
    price: 11.99,
    originalPrice: 14.99,
    category: "romance",
    genres: ["romance", "fiction"],
    rating: 4.4,
    reviewCount: 5678,
    description: "An unforgettable love story.",
    image: "/the-notebook-romance-love-story-book-cover.jpg",
    inStock: true,
    quantity: 33,
    featured: false,
    isbn: "978-0-446-67632-2",
    pages: 227,
    language: "English",
    publisher: "Grand Central",
    publishedDate: "1996-10-01",
    status: "active",
    createdAt: "2024-01-11T00:00:00Z",
  },
  {
    id: "12",
    title: "Charlotte's Web",
    authorId: "12",
    author: "E.B. White",
    sellerId: "2",
    price: 9.99,
    originalPrice: 12.99,
    category: "children",
    genres: ["children", "fiction"],
    rating: 4.8,
    reviewCount: 6789,
    description: "The beloved story of friendship between Wilbur and Charlotte.",
    image: "/charlottes-web-children-book-farm-animals.jpg",
    inStock: true,
    quantity: 55,
    featured: false,
    isbn: "978-0-06-440055-8",
    pages: 192,
    language: "English",
    publisher: "HarperCollins",
    publishedDate: "1952-10-15",
    status: "active",
    createdAt: "2024-01-12T00:00:00Z",
  },
]

export const BookModel = {
  getAll: () => books.filter((b) => b.status === "active"),

  getAllIncludingInactive: () => books,

  getById: (id) => books.find((b) => b.id === id),

  getByCategory: (category) => books.filter((b) => b.category === category && b.status === "active"),

  getByGenre: (genreId) => books.filter((b) => b.genres.includes(genreId) && b.status === "active"),

  getBySeller: (sellerId) => books.filter((b) => b.sellerId === sellerId),

  getFeatured: () => books.filter((b) => b.featured && b.status === "active"),

  search: (query) => {
    const q = query.toLowerCase()
    return books.filter(
      (b) =>
        b.status === "active" &&
        (b.title.toLowerCase().includes(q) ||
          b.author.toLowerCase().includes(q) ||
          b.description.toLowerCase().includes(q)),
    )
  },

  create: (bookData) => {
    const newBook = {
      ...bookData,
      id: Date.now().toString(),
      reviewCount: 0,
      rating: 0,
      status: "active",
      createdAt: new Date().toISOString(),
    }
    books.push(newBook)
    return newBook
  },

  update: (id, data) => {
    books = books.map((b) => (b.id === id ? { ...b, ...data } : b))
    return books.find((b) => b.id === id)
  },

  delete: (id) => {
    const book = books.find((b) => b.id === id)
    books = books.filter((b) => b.id !== id)
    return book
  },

  updateRating: (bookId, newRating, reviewCount) => {
    books = books.map((b) => (b.id === bookId ? { ...b, rating: newRating, reviewCount } : b))
    return books.find((b) => b.id === bookId)
  },

  count: () => books.filter((b) => b.status === "active").length,

  getLowStock: (threshold = 10) => books.filter((b) => b.quantity < threshold && b.status === "active"),
}
